### ISSUE TITLE
cl-macroexpand-all deprecated in Emacs 24.3

### ISSUE THREAD

**Issue by iamjasontumusiime** [bookest/arduino-mode#9]
It looks like arduino-mode uses cl-macroexpand-all which has been deprecated in favor of macroexpand-all so I'm getting this error "Symbol's function definition is void: cl-macroexpand-all" when I try to install it. See http://emacs.stackexchange.com/questions/2864/symbols-function-definition-is-void-cl-macroexpand-all-when-trying-to-instal. I am using emacs 24.4.

**Comment by bookest** [comment]
arduino-mode is derived from cc-mode, so it does look like you're running into the bug with 24.4 mentioned in that link:

http://debbugs.gnu.org/cgi/bugreport.cgi?bug=18845

Let me see if I can reproduce it and test out the solution mentioned there. In the meantime does loading cl prior to loading arduino-mode resolve the problem for you?

**Comment by iamjasontumusiime** [comment]
Sure, loading cl resolves the problem.

**Comment by bookest** [comment]
A fix for this was merged in #11.
